# @package _global_

defaults:
  - _self_
  - data: od
  - model: tgcn
  - callbacks: time
  - logger: tensorboard # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: time
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: D:\project\busODPredict\busODPredictor\logs\train\runs\2025-12-18_15-56-13\checkpoints\last.ckpt
